### ISSUE TITLE
YouTubeも欲しいな

### ISSUE THREAD

**Issue by sun-yryr** [sun-yryr/Rec-adio#24]

**Comment by chottokun** [comment]
[こんなんで](https://github.com/chottokun/yt_dl)　手抜きで作ってみました。
新着管理が出来たら組み込めるかも。

**Comment by chottokun** [comment]
キーワードで検索するとノイズが多すぎるので、チャンネル監視してみました。
[こちら](https://github.com/chottokun/yt_dl)です。放置して動くようになったのでコメント。

**Comment by sun-yryr** [comment]
まだ優先度が低いです。
- webuiをしっかり整備してローカルで見やすくする方が先決
- 動画で欲しいものもあるので（音泉・agqr含む）その辺も考慮したアーキテクチャにしたい

**Comment by sun-yryr** [comment]
一旦リセット！
