### ISSUE TITLE
A&GでFlash→HLS移行

### ISSUE THREAD

**Issue by sugawarayss** [sun-yryr/Rec-adio#63]
A&GがHLSに移行したため、録音できなくなった。

**Comment by sugawarayss** [comment]
↓で録音できるようです。
```
        file_path = dir_path + "/" + program_data["title"].replace(" ", "_") + "_" + program_data["ft"][:12]
        url = 'https://fms2.uniqueradio.jp/agqr10/aandg1.m3u8'
        duration = str(program_data["dur"] * 60)
        cwd = 'ffmpeg -i {0} -movflags faststart -t {1} {2}.mp3'.format(url, duration, file_path)
        subprocess.run(cwd=cwd, shell=True)
```

**Comment by chottokun** [comment]
別途、PRだしているんですが、お忙しいのかな。

**Comment by sugawarayss** [comment]
なるほど、失礼しました。
年末年始ですしね😓

m3u8のurlも定期？で変わるみたいで、コケました。

`aandg1 -> aandg3`
に変えたら動きました。

**Comment by chottokun** [comment]
コケてましたね。URLありがとうございます。
PRのんびり待ちます。
私、PRの作法も分かってないですし、そちらのほうが気になります（笑）

**Comment by sun-yryr** [comment]
@sugawarayss @chottokun 
いろいろありがとうございます。そしてリポジトリ見れてなくて申し訳ないです。
今今で認識したので（一旦自分で書いたissueはリセットして）徐々に手をつけていきます。
なので首を長くしてお待ちいただければと思います 🙇‍♂️
